// svelte-preview-ui/src/routes/error-boundary.svelte
<script>
  import { onMount } from "svelte";

  let hasError = false;
  let error;
  let errorInfo;

  onMount(async () => {
    try {
      if (!$$slots.default) {
        throw new Error("No default slot content provided");
      }
    } catch (e) {
      hasError = true;
      error = e;
      // populate errorInfo as needed
    }
  });
</script>

{#if hasError}
  <div class="p-4 bg-red-100 border border-red-400 text-red-700">
    <h1 class="text-lg font-bold">Something went wrong.</h1>

    {#if error}
      <pre class="overflow-auto text-sm mt-2 bg-red-50 p-2">
        <code>{error.toString()}</code>
      </pre>
    {/if}

    {#if errorInfo}
      <pre class="overflow-auto text-sm mt-2 bg-red-50 p-2">
        <code>{errorInfo.componentStack}</code>
      </pre>
    {/if}
  </div>
{:else}
  <slot />
{/if}

// preview-ui/src/ErrorBoundary.jsx
import React from "react";

export default class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false, error: null, errorInfo: null };
  }

  static getDerivedStateFromError() {
    return { hasError: true };
  }

  componentDidCatch(error, errorInfo) {
    this.setState({
      error: error,
      errorInfo: errorInfo,
    });
  }

  render() {
    if (this.state.hasError) {
      return (
        <div className="p-4 bg-red-100 border border-red-400 text-red-700">
          <h1 className="text-lg font-bold">Something went wrong.</h1>
          {this.state.error && (
            <pre className="overflow-auto text-sm mt-2 bg-red-50 p-2">
              <code>{this.state.error.toString()}</code>
            </pre>
          )}
          {this.state.errorInfo && (
            <pre className="overflow-auto text-sm mt-2 bg-red-50 p-2">
              <code>{this.state.errorInfo.componentStack}</code>
            </pre>
          )}
        </div>
      );
    }

    return this.props.children;
  }
}
